### ISSUE TITLE
NoMethodError: undefined method `instance' for Capistrano::Configuration:Class

### ISSUE THREAD

**Issue by pamio** [russ/lacquer#23]
I run through an issue after requiring `require 'lacquer/capistrano'` .

Here's the trace to the issue 

     cap staging deploy --trace
     cap aborted! 
     NoMethodError: undefined method `instance' for Capistrano::Configuration:Class
     /home/pamio/.rvm/gems/ruby-2.1.1/gems/lacquer-0.5.6/lib/lacquer/capistrano.rb:3:in `<top    (required)>'
     /home/pamio/dev/rails_apps/remote/khojguru/Capfile:15:in `require'
     /home/pamio/dev/rails_apps/remote/khojguru/Capfile:15:in `<top (required)>'
     /home/pamio/.rvm/gems/ruby-2.1.1/gems/rake-10.4.2/lib/rake/rake_module.rb:28:in `load'
     /home/pamio/.rvm/gems/ruby-2.1.1/gems/rake-10.4.2/lib/rake/rake_module.rb:28:in `load_rakefile'
     /home/pamio/.rvm/gems/ruby-2.1.1/gems/rake-10.4.2/lib/rake/application.rb:689:in  `raw_load_rakefile'
     /home/pamio/.rvm/gems/ruby-2.1.1/gems/rake-10.4.2/lib/rake/application.rb:94:in `block in load_rakefile'
     /home/pamio/.rvm/gems/ruby-2.1.1/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
     /home/pamio/.rvm/gems/ruby-2.1.1/gems/rake-10.4.2/lib/rake/application.rb:93:in `load_rakefile'
     /home/pamio/.rvm/gems/ruby-2.1.1/gems/rake-10.4.2/lib/rake/application.rb:77:in `block in run'
     /home/pamio/.rvm/gems/ruby-2.1.1/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
     /home/pamio/.rvm/gems/ruby-2.1.1/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
     /home/pamio/.rvm/gems/ruby-2.1.1/gems/capistrano-3.3.5/lib/capistrano/application.rb:15:in `run'
     /home/pamio/.rvm/gems/ruby-2.1.1/gems/capistrano-3.3.5/bin/cap:3:in `<top (required)>'
     /home/pamio/.rvm/gems/ruby-2.1.1/bin/cap:23:in `load'
     /home/pamio/.rvm/gems/ruby-2.1.1/bin/cap:23:in `<main>'
     /home/pamio/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
     /home/pamio/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'

Im on ruby 2.1.1 & rails 4.2.1. Any pointers on this ?

Thanks

**Comment by agarwalakash** [comment]
I m also facing the same issue. 
(Backtrace restricted to imported tasks)
cap aborted!
NoMethodError: undefined method `instance' for Capistrano::Configuration:Class
Did you mean?  instance_of?

Tasks: TOP => stagging
(See full trace by running task with --trace)

Ruby version is 2.3.1, Rails 4.2.7.1, Capistrano 3.10.1
